services:
  - type: web
    name: kaharova-server
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
